<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CustomPubSub.RabbitMq\CustomPubSub.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\CustomPubSub.WebSocket\CustomPubSub.WebSocket.csproj" />
  </ItemGroup>

</Project>
